# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en


ru:
  languageCode: ru
  contentDir: content/ru
  params:
    description: Site description in Chinese...
  menu:
    main:
      - name: Обо мне
        url: '#about'
        weight: 1
      - name: Посты
        url: '#posts'
        weight: 2
      - name: Проекты
        url: '#projects'
        weight: 3
      - name: Конференции
        url: '#talks'
        weight: 4
      - name: Публикации
        url: '#featured'
        weight: 5
      - name: Контакты
        url: '#contact'
        weight: 6
